FEATURE: SEO
silverstripe/bambusa-installer pull request #17
Opened 2019-07-09 03:15 UTC by unclecheese

Resolves: https://github.com/silverstripeltd/open-sourcerers/issues/83

2019-07-09 23:50 UTC, dnsl48 commented
I'm having 500 server error "Custom Meta Tags

2019-07-09 23:52 UTC, dnsl48 requested changes
meta tags management doesn't seem to be working

2019-07-11 02:10 UTC, unclecheese commented
@dnsl48 PR has been created for the issue, but it is resolved in another patch as you'll see. https://github.com/silverstripe/silverstripe-framework/pull/9119

2019-07-15 03:30 UTC, dnsl48 approved these changes

2019-07-15 03:30 UTC, merged