TravisCI / Building docker images
silverstripe/bambusa-installer pull request #3
Opened 2019-06-24 03:30 UTC by dnsl48

2019-06-27 00:56 UTC, chillu requested changes
Why isn't this using docker-compose? We'll need multiple images for eventual inclusion of Solr search via https://github.com/silverstripeltd/open-sourcerers/issues/86. https://github.com/silverstripeltd/cwp-demo-template/blob/master/docker-compose.yml

Also, a bit more "getting started" detail in the README would be good, https://github.com/silverstripeltd/cwp-demo-template already has that covered?

2019-06-27 01:08 UTC, dnsl48 commented
> Why isn't this using docker-compose?

docker compose implementation is out of scope for this task. It's not required for building the image, it's rather might facilitate spinning up development environment.

We can definitely do it, but I'm not sure we really need it at this point. At least until we start working on search functionality.

If we do it, I suggest we make a different PR for it (it'll be more granular then).

> Also, a bit more "getting started" detail in the README would be good, https://github.com/silverstripeltd/cwp-demo-template already has that covered?

It also depends on development environment. If we have a particular docker-compose implementation, then we could add it. But so far, it's not really different from any other project and can be run on any environment.

2019-06-27 21:41 UTC, chillu commented
Hah, touché. I've split this out into https://github.com/silverstripeltd/open-sourcerers/issues/107

2019-07-02 03:35 UTC, maxime-rainville requested changes
Won't your build always be green with this set up?

```yml
script:
  - true # vendor/bin/phpunit --testsuite bambusa
  - true # composer run-script lint
  - true # phpdbg -qrr vendor/bin/phpunit --testsuite bambusa --coverage-clover=coverage.xml
  - sh -e /etc/init.d/xvfb start
  - vendor/bin/serve --bootstrap-file vendor/silverstripe/cms/tests/behat/serve-bootstrap.php &> artifacts/serve.log &
  - sleep 3; chromedriver > artifacts/chromedriver.log 2>&1 &
  - true # vendor/bin/behat admin
```

I managed to build and push my own image up to docker hub. I also use my local sscom site to get running on SSP. So it seems to be working broadly OK.

2019-07-02 03:35 UTC, maxime-rainville commented on docker/Dockerfile
> + && yes '' | pecl install imagick && docker-php-ext-enable imagick \
We should only enable imagick if we plan on using it as our image library ... which we should.

2019-07-02 03:35 UTC, maxime-rainville commented on .travis.yml
>    - mysql
But MariaDB!!!

2019-07-02 03:39 UTC, dnsl48 commented
> Won't your build always be green with this set up?

It will indeed.
Unfortunately, the current state of bambusa-installer tests is too red. Making the tests green is out of scope for this task as its main goal is to build docker images.
I think we should fight red tests in a separate card.

2019-07-02 03:39 UTC, dnsl48 commented on docker/Dockerfile
> + && yes '' | pecl install imagick && docker-php-ext-enable imagick \
so, aren't we planning to use image magick? :)

2019-07-02 03:40 UTC, dnsl48 commented on .travis.yml
>    - mysql
unfortunately, mariadb is not available on our kubes stack :)

2019-07-02 03:43 UTC, maxime-rainville commented
If our current build is broken, then we probably shouldn't be pushing stuff to docker any way. 

If it's not holding us back, I would suggest turn on the build and let it fail. Call it an incentive to get those tests green.

2019-07-02 03:56 UTC, dnsl48 commented
I was aiming at particularly docker build logic in this PR. What do you think if we get it merged and then in another PR we actually add the tests running and then it blocks actual docker images deploy?

Currently, there's no other way to check the actual docker hub image deployment works, but only to ignore tests. And this PR only contains docker image build+deploy stuff, isolated from running tests and from what tests we run and from how exactly we run them.

2019-07-02 03:59 UTC, maxime-rainville commented
I'm OK approving this PR as-is as long as the requirement to only deploy to docker on green tests is captured somewhere else.

2019-07-02 04:00 UTC, maxime-rainville commented
Just don't want us to forget about it and start pushing broken images up.

2019-07-02 04:01 UTC, dnsl48 commented
I'll make another PR based on this branch which adds tests

2019-07-02 04:04 UTC, maxime-rainville commented on docker/Dockerfile
> + && yes '' | pecl install imagick && docker-php-ext-enable imagick \
I think we should use imagick, although the default is GD right now.

Just pointing out that if we don't enable imagick in the site config, there's no point including it in the docker image.

2019-07-02 04:04 UTC, maxime-rainville commented on .travis.yml
>    - mysql
:-(

2019-07-02 04:05 UTC, maxime-rainville approved these changes
I'm happy following the discussion with Serge.

2019-07-02 04:06 UTC, dnsl48 commented on docker/Dockerfile
> + && yes '' | pecl install imagick && docker-php-ext-enable imagick \
I think it's safe to leave it in until we make all the application level decisions. Then we should be able to tinker with the dockerfile and remove either GD or Imagemagick and other unnecessary libraries. Currently, that doesn't consume too much resources having both installed and available.

2019-07-02 04:08 UTC, dnsl48 commented on docker/Dockerfile
> + && yes '' | pecl install imagick && docker-php-ext-enable imagick \
However, if you feel strong about that I can remove it :) Just wanted to avoid making any application level decisions in this PR

2019-07-02 04:17 UTC, merged

2019-07-02 04:27 UTC, dnsl48 commented
I've made the other PR: https://github.com/silverstripe/bambusa-installer/pull/8