ENH / set up unsupported module versions more tightly
silverstripe/bambusa-installer pull request #30
Opened 2019-07-16 01:39 UTC by dnsl48

related https://github.com/silverstripeltd/open-sourcerers/issues/65

2019-07-18 05:01 UTC, maxime-rainville requested changes
I would keep `silverstripe/dynamodb` with a loose constraint.

The other ones I'm not too fuss about.

2019-07-18 05:01 UTC, maxime-rainville commented on composer.json
> +        "silverstripe/dynamodb": "~4.0.1",
"silverstripe/dynamodb" might has well be a supported module.

2019-07-18 05:01 UTC, maxime-rainville commented on composer.json
> +        "silverstripe/raygun": "~3.1.0",
"silverstripe/raygun" and "sminnee/tagmanager" are not officially supported, but I think it's safe to assume that we can trust the maintainers to stick to semver.

2019-07-18 05:03 UTC, dnsl48 commented on composer.json
> +        "silverstripe/dynamodb": "~4.0.1",
Ping @chillu 
I also reckon dynamodb must be a supported module, but it's not just yet :)

2019-07-18 09:20 UTC, chillu commented on composer.json
> +        "silverstripe/dynamodb": "~4.0.1",
That's irreleavnt to this pull request, right? I think a constraint to `~4.0` would be more appropriate. I think we can assume that module sticks to semver

2019-07-18 09:21 UTC, chillu commented on composer.json
> +        "silverstripe/raygun": "~3.1.0",
Yeah this is overkill, let's pull in minor releases automatically. There's no point getting notified via the new `composer outdated` if there's `raygun:3.2.0` available. I want to get notified when `raygun:4` is available.

2019-07-22 01:45 UTC, maxime-rainville commented on composer.json
> +        "silverstripe/dynamodb": "~4.0.1",
FYI `~4.0` is functionality equivalent to `^4.0.0`.

`~4.0.0` will let you upgrade to `4.0.1` but not `4.1.0`. `~4.0` and `^4.0.0` will both upgrade you to `4.1.0`

2019-07-22 23:42 UTC, dnsl48 commented
@maxime-rainville I've added the discussed changes, also added a fix for `bin/create-slack-message.php` so it only notifies about stable major upgrades

2019-07-23 05:30 UTC, maxime-rainville approved these changes

2019-07-23 05:30 UTC, merged